### ISSUE TITLE
No code available 

### ISSUE THREAD

**Issue by alwavshumilin** [DougDougGithub/ChatGodApp#1]
How I will be able to use DougGPT without actual code? Smh

**Comment by NightKiller2** [comment]
Rumor was the horses took the code..

**Comment by jlunder00** [comment]
This is the chat god app. wrong repo. there is also no code for the chat god app. please fix @DougDougGithub

**Comment by Melon-Bread** [comment]
Does anyone else hear a pipe dropping every now and then?

**Comment by AlessTheDev** [comment]
?

**Comment by AlessTheDev** [comment]
> Does anyone else hear a pipe dropping every now and then?

?

**Comment by Jelte2357** [comment]
> Does anyone else hear a pipe dropping every now and then?

What do you mean???

**Comment by alwavshumilin** [comment]
Is the repo dead? 10 minutes and still no code. Someone should adopt the whole project

**Comment by alwavshumilin** [comment]
WE DID IT CHAT
