### ISSUE TITLE
Not an issue but i would like if you could add youtube chat to the people who can be selected

### ISSUE THREAD

**Issue by Thisguyneedshelp** [DougDougGithub/ChatGodApp#13]
Not an issue but i would like if you could add youtube chat to the people who can be selected, i know you said youtube is difficult to work with but im sure you could figure it out in a simple 5 minute coding adventure. 
yours truly, your ex-wife                                                                                                       P.S: Only a bald dougdoug wouldnt fix this issue

**Comment by DougDougGithub** [comment]
Conceptually this is a good idea but this would take a substantial amount of additional work, there is not currently a good solution for reading Youtube chat, they do not officially support reading their chat so the only solutions are very janky and prone to issues. Someone else is welcome to try implementing this but I won't be attempting it myself

**Comment by Earthgames** [comment]
If someone want to do this, this [repo](https://github.com/BloopVerified/TwitchPlays-GUI) interacts with youtube chat by scraping it.
This happens in the [TwitchPlays_Connection file](https://github.com/BloopVerified/TwitchPlays-GUI/blob/main/TwitchPlays_Connection.py)
