### ISSUE TITLE
Issues are on

### ISSUE THREAD

**Issue by jlunder00** [DougDougGithub/ChatGodApp#5]
@DougDougGithub if you are not planning on maintaining/further developing this, or dont want to do so collaboratively, it may be a good idea to turn off issues on this repository, otherwise people will be able to create a bunch of useless issues like this.

Here's instructions: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues

**Comment by alwavshumilin** [comment]
On the serious note, all the hype will be gone within 15 minutes after the stream. Feels like it’s okay to leave them be just in case. TwitchChatPlays repo is the great example

**Comment by jlunder00** [comment]
maybe, but he also didnt upload that on stream. its nbd anyways
