### ISSUE TITLE
Actual suggestion: Put each shared python module into its own repository

### ISSUE THREAD

**Issue by qwertychouskie** [DougDougGithub/ChatGodApp#9]
For example, your OBS Websockets code that is shared across your projects should be in its own repository, so that if you make later changes, you don't have to copy those changes to every git repository.

**Comment by lliam-mcbean** [comment]
> For example, your OBS Websockets code that is shared across your projects should be in its own repository, so that if you make later changes, you don't have to copy those changes to every git repository.

the obs code here is very different from the obs in pajama sam. they both interact uniquely with obs and display different graphics. what he is doing is fine. also he doesnt seem to use github as a personal code manager but more just to give us the code. He only has 2 repos and they were just made recently
